services:
  - type: web
    name: proyfrontendgrupo08
    env: static
    staticPublishPath: dist/proyfrontendgrupo08
    buildCommand: npm install && npm run build
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html